# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ai < Formula
  desc "AI shell assistant — turn natural language into shell commands"
  homepage "https://github.com/hra42/ai"
  version "0.1.0"
  license "Unlicense"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hra42/ai/releases/download/v0.1.0/ai_darwin_amd64.tar.gz"
      sha256 "28e0661598284497186dc5fdce741bde91400276c97c5d04584ab2452fb3ffab"

      define_method(:install) do
        bin.install "ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hra42/ai/releases/download/v0.1.0/ai_darwin_arm64.tar.gz"
      sha256 "39cf6599bd2f04ac280f67437c689c1e15fe75f59e5a060784ad6844bb6e9e37"

      define_method(:install) do
        bin.install "ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hra42/ai/releases/download/v0.1.0/ai_linux_amd64.tar.gz"
      sha256 "420bb352e046f74abe081f5e3a8d4cf55b81e9c54a7455c750366d557b0ee07d"
      define_method(:install) do
        bin.install "ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hra42/ai/releases/download/v0.1.0/ai_linux_arm64.tar.gz"
      sha256 "17c223fb8445d7f07fa82236e87f9ec8b51c65ddc72a5a2101cc13f806e8df86"
      define_method(:install) do
        bin.install "ai"
      end
    end
  end

  test do
    system "#{bin}/ai", "--version"
  end
end
